server:
  port: 80

zuul:
  ignoredServices: '*'
  routes:
    scherule-auth:
      path: /oauth/**
      serviceId: scherule-users
      stripPrefix: false
      sensitive-headers:
    scherule-users:
      path: /api/users/**
      sensitive-headers:
    scherule-calendaring:
      path: /api/calendaring/**
      sensitive-headers:
  add-proxy-headers: true

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${HOST:localhost}
    non-secure-port: ${server.port}
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 20
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:10000/eureka/}

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO

---
spring:
  profiles: dev
logging:
  level:
    org.springframework.security: DEBUG
